export enum USER_ACTION_TYPES  {
    SET_CURRENT_USER= 'User/SET_CURRENT_USER',
    CHECK_USER_SESSION= 'USER/CHECK_USER_SESSION',
    GOOGLE_SIGN_IN_START= 'USER/GOOGLE_SIGN_IN_START',
    EMAIL_SIGN_IN_START= 'USER/EMAIL_SIGN_IN_START',
    SIGN_IN_SUCCESS= 'USER/SIGN_IN_SUCCESS',
    SIGN_IN_FAILED= 'USER/SIGN_IN_FAILED',
    SIGN_UP_START= 'USER/SIGN_UP_START',
    SIGN_UP_SUCCESS= 'USER/SIGN_UP_SUCCESS',
    SIGN_UP_FAILED= 'USER/SIGN_UP_FAILED',
    SIGN_OUT_START= 'USER/SIGN_OUT_START',
    SIGN_OUT_SUCCESS= 'USER/SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILED= 'USER/SIGN_OUT_FAILED',
}