export const CATEGORY_ACTION_TYPES = {
    SET_CATEGORIES: 'Category/SET_CATEGORIES',
    FETCH_CATEGORIES_START: 'Category/FETCH_CATEGORIES_START',
    FETCH_CATEGORIES_SUCCESS: 'Category/FETCH_CATEGORIES_SUCCESS',
    FETCH_CATEGORIES_FAIL: 'Category/FETCH_CATEGORIES_FAIL'
}